version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 20221

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 20221

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 20221
      ME_CONFIG_MONGODB_URL: mongodb://root:20221@mongo:27017/

  tltask:
    image: tltask
    depends_on:
      - db
      - mongo
      - adminer
      - mongo-express
    volumes:
      - "./data:/usr/src/app/data"
    environment:
      NOSQLDB_HOST: mongo
      NOSQLDB_USER: root
      NOSQLDB_PASS: 20221
      SQLDB_HOST: db
      SQLDB_USER: postgres
      SQLDB_PASS: 20221